services:
  - type: web
    name: schoolabe-be
    env: node
    repo: https://github.com/Rohitsrivastva1/schoolabe-be.git
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DIALECT
        sync: false
